### ISSUE TITLE
Use utf-8 in logger

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#107]
I have cloned site, which has Cyrillic symbols in paths. And I got this error:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 989, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 112-115: ordinal not in range(128)
Call stack:
  File "/opt/tanner/bin/tanner", line 33, in <module>
    main()
  File "/opt/tanner/bin/tanner", line 29, in main
    tanner.server.run_server()
  File "/opt/tanner/tanner/server.py", line 132, in run_server
    loop.run_forever()
  File "/usr/lib/python3.6/site-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "/opt/tanner/tanner/server.py", line 89, in handle_request
    response_msg = yield from self.handle_event(data, self.redis_client)
  File "/opt/tanner/tanner/server.py", line 54, in handle_event
    self.logger.info('Requested path %s', path)
Message: 'Requested path %s'
Arguments: ('/sites/default/files/images/фото яковец.jpg',)
```

**Comment by rnehra01** [comment]
To resolve it, we just have to replace logger.info(string.encode('utf-8')) everywhere in the code?Anything else do we have to do?

**Comment by afeena** [comment]
Not exactly, we can set encoding while logger setup
