### ISSUE TITLE
SQLi check post exception

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#146]
```
2017-06-04 10:10 ERROR:aiohttp.server:log_exception: Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 421, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 303, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/server.py", line 56, in handle_event
    detection = await self.base_handler.handle(data, session, path)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/base.py", line 77, in handle
    detection = await self.emulate(data, session, path)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/base.py", line 70, in emulate
    detection = await self.handle_post(session, data)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/base.py", line 32, in handle_post
    sqli_data = await self.emulators['sqli'].check_post_data(data)
TypeError: object list can't be used in 'await' expression
```

**Comment by rnehra01** [comment]
@afeena We can close this.
