### ISSUE TITLE
Sqlite result problem in new communication system

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#190]
In develop branch I've found the problem in result.
```/hide?goto=(select(0)from(select(sleep(10)))v)/*%27%20(select(0)from(select(sleep(10)))v)%20%27%22%20(select(0)from(select(sleep(10)))v)%20%22*/&id[]=14619725```
Such query and similar gives the error:
```
ERROR:aiohttp.server:log_exception: Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 421, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.5/site-packages/aiohttp/web.py", line 303, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.5/site-packages/Tanner-0.4.0-py3.5.egg/tanner/server.py", line 55, in handle_event
    detection = await self.base_handler.handle(data, session)
  File "/usr/local/lib/python3.5/site-packages/Tanner-0.4.0-py3.5.egg/tanner/emulators/base.py", line 134, in handle
    detection = await self.emulate(data, session)
  File "/usr/local/lib/python3.5/site-packages/Tanner-0.4.0-py3.5.egg/tanner/emulators/base.py", line 123, in emulate
    if detection['payload']['page']:
TypeError: string indices must be integers
```

detection result:
```
{'payload': 'You have an error in your SQL syntax; check the manual                        that corresponds to your MySQL server version for the
        right syntax to use near goto at line 1', 'order': 2, 'name': 'sqli'}
```

**Comment by afeena** [comment]
#193
