### ISSUE TITLE
Error when reading INI config file - convert string to int type

### ISSUE THREAD

**Issue by standa4** [mushorg/tanner#196]
Hello,
I found the bug in tanner. When you specify the config file the tanner ends with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/tanner", line 4, in <module>
    __import__('pkg_resources').run_script('Tanner==0.4.0', 'tanner')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.4.0-py3.5.egg/EGG-INFO/scripts/tanner", line 36, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.4.0-py3.5.egg/EGG-INFO/scripts/tanner", line 32, in main
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.4.0-py3.5.egg/tanner/server.py", line 101, in start
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 435, in run_app
    backlog=backlog)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 336, in _make_server_creators
    base_url = URL('{}://localhost'.format(scheme)).with_port(port)
  File "/usr/local/lib/python3.5/dist-packages/yarl/__init__.py", line 703, in with_port
    "port should be int or None, got {}".format(type(port)))
TypeError: port should be int or None, got <class 'str'>
```

The config parser reads the values as string so the numerical values should be converted to proper type or read with use of getint function.

Thank you.

Stanislav

**Comment by afeena** [comment]
Hi Stanislav, I've made a hot fix for you :) #197 
Thanks!
