### ISSUE TITLE
configparser error in configure file

### ISSUE THREAD

**Issue by Dudaew** [mushorg/tanner#203]
Every time trying to specify any configuration (e.g tanner/tanner/tests/test_config.py) there is such output
```
Traceback (most recent call last):
  File "/usr/local/bin/tanner", line 4, in <module>
    __import__('pkg_resources').run_script('Tanner==0.4.0', 'tanner')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.4.0-py3.5.egg/EGG-INFO/scripts/tanner", line 36, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.4.0-py3.5.egg/EGG-INFO/scripts/tanner", line 23, in main
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.4.0-py3.5.egg/tanner/config.py", line 35, in set_config
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/opt/tannerINST/tanner/tests/test_config.py', line: 1
'import configparser\n'
```

what is the trouble? 
Thank you.

**Comment by afeena** [comment]
Hi @Dudaew 
Could you please show me your config?

**Comment by Dudaew** [comment]
```
import configparser
import os
import unittest

from tanner import config

class TestCongif(unittest.TestCase):
    def setUp(self):
        config.TannerConfig.config = None
        self.d = {
            'DATA': {'db_config': '/tmp/user_tanner/db/db_config.json', 'dorks': '/tmp/user_tanner/data/dorks.pickle',
                     'user_dorks': '/tmp/user_tanner/data/user_dorks.pickle',
                     'vdocs': '/tmp/user_tanner/data/vdocs.json'},
            'TANNER': {'host': '0.0.0.0', 'port': '9000'},
            'WEB': {'host': '0.0.0.0', 'port': '9001'},
            'WEB': {'host': '0.0.0.0', 'port': '9002'},
            'REDIS': {'host': 'localhost', 'port': '1337', 'poolsize': '40', 'timeout': '5'},
            'EMULATORS': {'root_dir': '/opt/tanner'},
            'EMULATOR_ENABLED': {'sqli': 'True', 'rfi': 'True', 'lfi': 'True', 'xss': 'True', 'cmd_exec': 'True'},
            'SQLI': {'type':'SQLITE', 'db_name': 'user_tanner_db', 'host':'localhost', 'user':'user_name', 'password':'user_pass'},
            'DOCKER': {'host_image': 'test_image'},
                        'LOGGER': {'log_debug': '/opt/tanner/tanner.log', 'log_err': '/opt/tanner/tanner.err'},
            'MONGO': {'enabled': 'False', 'URI': 'mongodb://localhost'},
            'LOCALLOG': {'enabled': 'False', 'PATH': '/tmp/user_tanner_report.json'}
            }

        self.valid_config_path = '/opt/tannerINST/tanner/config.ini'
        self.cfg = configparser.ConfigParser()
        if not os.path.exists(self.valid_config_path):
            for section in self.d:
                self.cfg.add_section(section)
                for value, data in self.d[section].items():
                    self.cfg.set(section, value, data)
            f = open(self.valid_config_path, 'w')
            self.cfg.write(f)
        else:
            self.cfg.read(self.valid_config_path)

        self.invalid_config_path = '/random/random_name'

    def test_set_config_when_file_exists(self):
        config.TannerConfig.set_config(self.valid_config_path)
        self.assertIsNotNone(config.TannerConfig.config)

    def test_set_config_when_file_dont_exists(self):
        with self.assertRaises(SystemExit):
            config.TannerConfig.set_config(self.invalid_config_path)
        self.assertIsNone(config.TannerConfig.config)

    def test_get_when_file_exists(self):
        config.TannerConfig.config = self.cfg
        for section in self.d:
            for value, assertion_data in self.d[section].items():
                data = config.TannerConfig.get(section, value)
                self.assertEqual(data, assertion_data)
    
     def test_get_when_file_dont_exists(self):
        config_template = {
            'DATA': {'db_config': '/opt/tanner/db/db_config.json', 'dorks': '/opt/tanner/data/dorks.pickle',
                     'user_dorks': '/opt/tanner/data/user_dorks.pickle',
                     'vdocs': '/opt/tanner/data/vdocs.json'},
            'TANNER': {'host': '0.0.0.0', 'port': 8090},
            'WEB': {'host': '0.0.0.0', 'port': 8091},
            'API': {'host': '0.0.0.0', 'port': 8092},
            'REDIS': {'host': 'localhost', 'port': 6379, 'poolsize': 80, 'timeout': 1},
            'EMULATORS': {'root_dir': '/opt/tanner'},
            'EMULATOR_ENABLED': {'sqli': 'True', 'rfi': 'True', 'lfi': 'True', 'xss': 'True', 'cmd_exec': 'True'},
            'SQLI': {'type':'SQLITE', 'db_name': 'tanner_db', 'host':'localhost', 'user':'root', 'password':'user_pass'},
            'DOCKER': {'host_image': 'busybox:latest'},
            'LOGGER': {'log_debug': '/opt/tanner/tanner.log', 'log_err': '/opt/tanner/tanner.err'},
            'MONGO': {'enabled': 'False', 'URI': 'mongodb://localhost'},
            'LOCALLOG': {'enabled': 'False', 'PATH': '/tmp/tanner_report.json'}
            }

        for section in config_template:
            for value, assertion_data in config_template[section].items():
                data = config.TannerConfig.get(section, value)
                self.assertEqual(data, assertion_data)

```
I`m not a python expert, so couldn`t find appropriate solution

**Comment by afeena** [comment]
This is the unittests for config, not a config. How you tried to setup config?

**Comment by Dudaew** [comment]
So, as far as I understood, I have to write config file by my own, right? There are no ready config,

**Comment by Dudaew** [comment]
As far as I understood, I have to write config file by my own, right? Or there is ready config, but I just could not found it?

**Comment by afeena** [comment]
If you want to define you own parameters, you can define INI config and pass `--config` parameter to the tanner.
We don't have sample config file, but you can look at the docs https://github.com/mushorg/tanner/blob/master/docs/source/config.rst

If you still have a questions, just ask :)

**Comment by Dudaew** [comment]
Thank you) Now I know the way to move
