### ISSUE TITLE
Connection pool problem

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#218]
```
2017-11-29 09:04 ERROR:aiohttp.server:log_exception: Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 421, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 303, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/Tanner-0.4.0-py3.6.egg/tanner/server.py", line 59, in handle_event
    data, self.redis_client
  File "/usr/lib/python3.6/site-packages/Tanner-0.4.0-py3.6.egg/tanner/session_manager.py", line 22, in add_or_update_session
    await redis_client.sadd('snare_ids', [valid_data['uuid']])
  File "/usr/lib/python3.6/site-packages/asyncio_redis/pool.py", line 119, in __getattr__
    self.poolsize, self.connections_in_use, self.connections_connected))
asyncio_redis.exceptions.NoAvailableConnectionsInPoolError: No available connections in the pool: size=80, in_use=80, connected=80
```

**Comment by glaslos** [comment]
Seems like we fail to close some redis connections.

**Comment by viskey98** [comment]
@afeena Can you tell me how to reproduce this problem :)

**Comment by afeena** [comment]
@viskey98 to be honest, I don't know how to reproduce this bug. That is why it can be hard to fix. Maybe someone will have it again and we wil get more info.

**Comment by glaslos** [comment]
@viskey98 if you are interested in exploring this issue, have a look where we connect to Redis and if there are any exceptions/error states that might leave a connection open and create a new one.

**Comment by viskey98** [comment]
I am working on this issue :)

**Comment by viskey98** [comment]
@glaslos  Can you please explain a bit, why could this happen. Because when I went through the code, I found that we delete the connections when they expire. Does this mean the pool size is not sufficient or is there something else which is causing this problem?

**Comment by afeena** [comment]
#259
