### ISSUE TITLE
Tanner-web not starting

### ISSUE THREAD

**Issue by viskey98** [mushorg/tanner#235]
I tried running tanner-web inside tanner folder, I get this following error:
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 401, in __init__
    raise ValueError('Not a directory')
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tannerweb", line 4, in <module>
    __import__('pkg_resources').run_script('Tanner==0.5.0', 'tannerweb')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/EGG-INFO/scripts/tannerweb", line 20, in <module>
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/EGG-INFO/scripts/tannerweb", line 16, in main
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/tanner/web/server.py", line 117, in start
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/tanner/web/server.py", line 110, in create_app
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/tanner/web/server.py", line 103, in setup_routes
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 850, in add_static
    follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 404, in __init__
    "No directory exists at '{}'".format(directory)) from error
ValueError: No directory exists at '/tanner/web/static'

```

**Comment by viskey98** [comment]
@afeena I tried running inside the tanner folder, I still get this error

**Comment by mzfr** [comment]
@viskey98 just by having look I think you are missing some directory in there.
Most probably `/tanner/web/static`

**Comment by afeena** [comment]
I run in the root of the tanner directory and it works fine for me. Please try to run it from folder, where you can access `/tanner/web/static`

**Comment by viskey98** [comment]
I think there was some trouble while setting up tanner, I again ran
`python3 setup.py install` and then ran tannerweb in tanner's root folder, it worked .

**Comment by viskey98** [comment]
@afeena Now, I have a snare instance connected to the tanner and also tannerweb running. How to access the web UI of tanner? ie the one where i can see the snare sessions? 
 I tried using http://0.0.0.0:8091/ it simply says a message 
`Tanner Web`

**Comment by mzfr** [comment]
@viskey98  see [this](http://tanner.readthedocs.io/en/latest/api.html)

**Comment by viskey98** [comment]
@mzfr Thank you
