### ISSUE TITLE
Certificate error when loading RFI from remote site

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/tanner#251]
When trying to load RFI from a remote site via SSL / TLS a certificate error is produced if hostname / FQDN are not identical with the one from the certificate. As a result the remote malware file is not loaded.

```
2018-05-28 21:31:13 ERROR:aiohttp.server:log_exception: Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/Tanner-0.5.0-py3.6.egg/tanner/server.py", line 64, in handle_event
    detection = await self.base_handler.handle(data, session)
  File "/usr/lib/python3.6/site-packages/Tanner-0.5.0-py3.6.egg/tanner/emulators/base.py", line 136, in handle
    detection = await self.emulate(data, session)
  File "/usr/lib/python3.6/site-packages/Tanner-0.5.0-py3.6.egg/tanner/emulators/base.py", line 118, in emulate
    detection = await self.handle_get(session, data)
  File "/usr/lib/python3.6/site-packages/Tanner-0.5.0-py3.6.egg/tanner/emulators/base.py", line 94, in handle_get
    possible_get_detection = await self.get_emulation_result(session, get_data, self.get_emulators)
  File "/usr/lib/python3.6/site-packages/Tanner-0.5.0-py3.6.egg/tanner/emulators/base.py", line 66, in get_emulation_result
    emulation_result = await self.emulators[detection['name']].handle(attack_params[detection['name']], session)
  File "/usr/lib/python3.6/site-packages/Tanner-0.5.0-py3.6.egg/tanner/emulators/rfi.py", line 101, in handle
    result = await self.get_rfi_result(attack_params[0]['value'])
  File "/usr/lib/python3.6/site-packages/Tanner-0.5.0-py3.6.egg/tanner/emulators/rfi.py", line 75, in get_rfi_result
    file_name = await self.download_file(path)
  File "/usr/lib/python3.6/site-packages/Tanner-0.5.0-py3.6.egg/tanner/emulators/rfi.py", line 43, in download_file
    async with await client.get(url) as resp:
  File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 632, in __await__
    resp = yield from self._coro
  File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 687, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 710, in _create_direct_connection
    local_addr=self._local_addr)
  File "uvloop/loop.pyx", line 1769, in create_connection
  File "uvloop/handles/stream.pyx", line 784, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/handles/stream.pyx", line 563, in uvloop.loop.UVStream._on_read
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 694, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 331, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'evil.com' doesn't match 'pure.evil.com'
```

**Comment by glaslos** [comment]
I assume ignoring the invalid certificate would be an option? Maybe make it optional via a flag?

**Comment by t3chn0m4g3** [comment]
Yes 👍

**Comment by t3chn0m4g3** [comment]
Any progress on this?

**Comment by t3chn0m4g3** [comment]
Can someone please have a look 😃 T-Pot 18.10 will have SNARE / TANNER as default web honeypot and it would be awesome if there was a solution for that 👼

**Comment by t3chn0m4g3** [comment]
@afeena Maybe something for GSoC 2020 😇 ?

**Comment by afeena** [comment]
@t3chn0m4g3 Oh shit, I am terribly sorry that no one take care of that till now :( I will take a look today and if it is something I can fix fast, I will do it

**Comment by t3chn0m4g3** [comment]
Thank you 🎉 😄
