### ISSUE TITLE
ERROR:aiohttp.server:log_exception: Error handling request

### ISSUE THREAD

**Issue by M1dor1ya** [mushorg/tanner#280]
I built snare and tanner in my machine and used IBM Security AppScan Standard to test the web site.
After the test,i can't visit the web site anymore.The following is the error message in the snare.err

2018-10-25 01:52:34 ERROR:aiohttp.server:log_exception: Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/middlewares.py", line 21, in error_middleware
    response = await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/server.py", line 50, in handle_request
    event_result = await self.tanner_handler.submit_data(data)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/tanner_handler.py", line 62, in submit_data
    raise e
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/tanner_handler.py", line 56, in submit_data
    event_result = await r.json()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'
2018-10-25 01:53:03 ERROR:aiohttp.server:log_exception: Error handling request
2018-10-25 01:53:03 ERROR:aiohttp.server:log_exception: Error handling request
2018-10-25 01:53:03 ERROR:aiohttp.server:log_exception: Error handling request
2018-10-25 01:53:03 ERROR:aiohttp.server:log_exception: Error handling request
2018-10-25 01:53:03 ERROR:aiohttp.server:log_exception: Error handling request
2018-10-25 01:53:03 ERROR:aiohttp.server:log_exception: Error handling request

**Comment by afeena** [comment]
@zhang199653 Hi, could you please give m a request which  causes this error?

**Comment by zhang199653** [comment]
@afeena  I still want to ask another question.Cmd Execution Emulator will let the cmd be executed in  container.If container has been destroyed,will tanner rebuild another container?

Thanks

**Comment by afeena** [comment]
@zhang199653 yes, basically, container is created for every session on request. if container doesn't exist, it will be recreated.
