### ISSUE TITLE
Bugs in RFI and PHP Code Injection Emulator

### ISSUE THREAD

**Issue by M1dor1ya** [mushorg/tanner#286]
When i was testing RFI and PHP Code Injection Emulator,I found two bugs.
```
RFI, URL: 192.168.2.8/?id=ftp://ftp.sunet.se/robots.txt
err msg:
2018-12-06 10:42:50 ERROR:aiohttp.server:log_exception: Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/server.py", line 64, in handle_event
    detection = await self.base_handler.handle(data, session)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/emulators/base.py", line 136, in handle
    detection = await self.emulate(data, session)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/emulators/base.py", line 118, in emulate
    detection = await self.handle_get(session, data)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/emulators/base.py", line 94, in handle_get
    possible_get_detection = await self.get_emulation_result(session, get_data, self.get_emulators)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/emulators/base.py", line 66, in get_emulation_result
    emulation_result = await self.emulators[detection['name']].handle(attack_params[detection['name']], session)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/emulators/rfi.py", line 101, in handle
    result = await self.get_rfi_result(attack_params[0]['value'])
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/emulators/rfi.py", line 86, in get_rfi_result
    rfi_result = await resp.json(content_type=None)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 947, in json
    return loads(stripped.decode(encoding))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

PHP Code Injection, URL: 192.168.2.8/?arg=1; phpinfo()
err msg:
2018-12-06 10:45:17 ERROR:tanner.php_code_injecton:get_injection_result: Error during connection to php sandbox 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'

I've tried the solution by : https://stackoverflow.com/questions/48840378/python-attempt-to-decode-json-with-unexpected-mimetype
But it still hasn't solved the problem.

**Comment by glaslos** [comment]
Can you check if the error still exists with the recently merged PR?

**Comment by M1dor1ya** [comment]
After i update the version of php sandbox,the bug was solved.Thanks!
