### ISSUE TITLE
error when running tanner

### ISSUE THREAD

**Issue by Moooser** [mushorg/tanner#350]
Running Tanner results in following error:
- I am running on Ubuntu 16.04
- Firewall is disabled
sudo tanner

      _________    _   ___   ____________
     /_  __/   |  / | / / | / / ____/ __ \
      / / / /| | /  |/ /  |/ / __/ / /_/ /
     / / / ___ |/ /|  / /|  / /___/ _, _/
    /_/ /_/  |_/_/ |_/_/ |_/_____/_/ |_|

Debug logs will be stored in /opt/tanner/tanner.log
Error logs will be stored in /opt/tanner/tanner.err
Traceback (most recent call last):
  File "/usr/local/bin/tanner", line 4, in <module>
    __import__('pkg_resources').run_script('Tanner==0.6.0', 'tanner')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/EGG-INFO/scripts/tanner", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/EGG-INFO/scripts/tanner", line 31, in main
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/server.py", line 117, in start
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/redis_client.py", line 22, in get_redis_client
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/odroid/.local/lib/python3.6/site-packages/aioredis/commands/__init__.py", line 198, in create_redis_pool
    loop=loop)
  File "/home/odroid/.local/lib/python3.6/site-packages/aioredis/pool.py", line 56, in create_pool
    await pool._fill_free(override_min=False)
  File "/home/odroid/.local/lib/python3.6/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/home/odroid/.local/lib/python3.6/site-packages/aioredis/connection.py", line 108, in create_connection
    timeout, loop=loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/home/odroid/.local/lib/python3.6/site-packages/aioredis/stream.py", line 19, in open_connection
    lambda: protocol, host, port, **kwds)
  File "uvloop/loop.pyx", line 1927, in create_connection
  File "uvloop/loop.pyx", line 1906, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "/home/odroid/.local/lib/python3.6/site-packages/aiohttp/client.py", line 314, in __del__
    self._loop.call_exception_handler(context)
Message: 'Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0xb52845d0>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "/home/odroid/.local/lib/python3.6/site-packages/aiohttp/client.py", line 314, in __del__
    self._loop.call_exception_handler(context)
Message: 'Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0xb5284990>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "/home/odroid/.local/lib/python3.6/site-packages/aiohttp/client.py", line 314, in __del__
    self._loop.call_exception_handler(context)
Message: 'Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0xb5284d70>'
Arguments: ()

**Comment by afeena** [comment]
Hi @Moooser 
Please provide some more info :)
I see some redis errors in your log, do you have redis running?

**Comment by Moooser** [comment]
ok my bad, I didn't thought that redis was a dependency. its running now, thanks for your help.
