### ISSUE TITLE
Configuration File issue: Want to enable tanner_report.json

### ISSUE THREAD

**Issue by layeha9600** [mushorg/tanner#386]
Hello,
I want to enable the **tanner_report.json** option. Can you please suggest what is the right default config file where I can change tanner_report.json to be enabled in LOCALLOG section ??
I have also tried with config.ini file with --config parameter but it is getting some error as --
      _________    _   ___   ____________
     /_  __/   |  / | / / | / / ____/ __ \
      / / / /| | /  |/ /  |/ / __/ / /_/ /
     / / / ___ |/ /|  / /|  / /___/ _, _/
    /_/ /_/  |_/_/ |_/_/ |_/_____/_/ |_|

Traceback (most recent call last):
  File "/usr/local/bin/tanner", line 4, in <module>
    __import__('pkg_resources').run_script('Tanner==0.6.0', 'tanner')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/EGG-INFO/scripts/tanner", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/EGG-INFO/scripts/tanner", line 22, in main
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.6.0-py3.6.egg/tanner/config.py", line 52, in set_config
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'config.ini', line: 1
"{'DATA': {'db_config': '/opt/tanner/db/db_config.json',\n"

**Comment by afeena** [comment]
Hi @layeha9600 
Sorry for the late answer, could you please provide the config.ini file you've tried to use?
