### ISSUE TITLE
TannerWeb Redis issue

### ISSUE THREAD

**Issue by danielkelley743** [mushorg/tanner#413]
Thoughts on ways to fix this? Keep getting it when running tannerweb - API and Tanner runs fine.

```

> tannerweb error message:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_urldispatcher.py", line 553, in __init__
>     raise ValueError("Not a directory")
> ValueError: Not a directory
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/tannerweb", line 4, in <module>
>     __import__('pkg_resources').run_script('Tanner==0.6.0', 'tannerweb')
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
>     exec(script_code, namespace, namespace)
>   File "/usr/local/lib/python3.8/dist-packages/Tanner-0.6.0-py3.8.egg/EGG-INFO/scripts/tannerweb", line 20, in <module>
>   File "/usr/local/lib/python3.8/dist-packages/Tanner-0.6.0-py3.8.egg/EGG-INFO/scripts/tannerweb", line 16, in main
>   File "/usr/local/lib/python3.8/dist-packages/Tanner-0.6.0-py3.8.egg/tanner/web/server.py", line 108, in start
>   File "/usr/local/lib/python3.8/dist-packages/Tanner-0.6.0-py3.8.egg/tanner/web/server.py", line 101, in create_app
>   File "/usr/local/lib/python3.8/dist-packages/Tanner-0.6.0-py3.8.egg/tanner/web/server.py", line 95, in setup_routes
>   File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_urldispatcher.py", line 1118, in add_static
>     resource = StaticResource(
>   File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_urldispatcher.py", line 555, in __init__
>     raise ValueError(f"No directory exists at '{directory}'") from error
> ValueError: No directory exists at '/home/test/env3/bin/tanner/web/static'
> Task was destroyed but it is pending!
> task: <Task pending name='Task-3' coro=<RedisConnection._read_data() running at /usr/local/lib/python3.8/dist-packages/aioredis/connection.py:186> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7feb056a4e80>()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /usr/local/lib/python3.8/dist-packages/aioredis/connection.py:168]>

```

**Comment by afeena** [comment]
Hi @danielkelley743 
how you run tannerwb?

**Comment by afeena** [comment]
Please look at the similar issue 
https://github.com/mushorg/tanner/issues/403
