### ISSUE TITLE
OverflowError: timeout is too large

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#50]
I'm testing SNARE/TANNER with grabber.
``` grabber --spider 1 --include --url <snare host url>``` ,
and OWASP Zap. LFI testing going well, but when starting testing RFI, it fails with this error:

```
Traceback (most recent call last):
  File "server.py", line 128, in <module>
    loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1262, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
OverflowError: timeout is too large
Task was destroyed but it is pending!
task: <Task pending coro=<ServerHttpProtocol.start() running at /usr/local/lib/python3.5/dist-packages/aiohttp-0.22.0a0-py3.5.egg/aiohttp/server.py:266> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_connect_done(10)(), Task._wakeup()]>>
Exception ignored in: <generator object ServerHttpProtocol.start at 0x7ff2725cbbf8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-0.22.0a0-py3.5.egg/aiohttp/server.py", line 312, in start
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 568, in close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 483, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 492, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 320, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by glaslos** [comment]
Can you try with a local SNARE and TANNER?

**Comment by afeena** [comment]
Yes, I tested it on the local machine

**Comment by glaslos** [comment]
Strange issue. Did you manage to reproduce or pinpoint where the issue is happening?

**Comment by afeena** [comment]
The problem is in the url, it can't handle google.com url, but grabber and owasp use it for testing

```
/Browse_Item_Details.asp?Store_Id=http%3A%2F%2Fwww.google.com%2F
/*.php?secc=http%3A%2F%2Fwww.google.com%2F
/Browse_Item_Details.asp?Store_Id=http%3A%2F%2Fwww.google.com%3A80%2F
/*.php?secc=http%3A%2F%2Fwww.google.com%3A80%2F
/Browse_Item_Details.asp?Store_Id=http%3A%2F%2Fwww.google.com
/*.php?secc=http%3A%2F%2Fwww.google.com
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/afeena/tanner/server.py", line 128, in <module>
    loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1262, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
OverflowError: timeout is too large
```

```
/print.php?page=http://google.com
Traceback (most recent call last):
  File "/home/afeena/tanner/server.py", line 128, in <module>
    loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1262, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
OverflowError: timeout is too large
Task was destroyed but it is pending!
task: <Task pending coro=<ServerHttpProtocol.start() running at /usr/local/lib/python3.5/dist-packages/aiohttp-0.22.0a0-py3.5.egg/aiohttp/server.py:266> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_connect_done(10)(), Task._wakeup()]>>
Exception ignored in: <generator object ServerHttpProtocol.start at 0x7f7b96d5c570>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-0.22.0a0-py3.5.egg/aiohttp/server.py", line 312, in start
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 568, in close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 483, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 492, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 320, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by afeena** [comment]
I spent lots of time trying to understand the problem. It seems that this error occurs only on my local Ubuntu 16.04 LTS and there is no errors on Arch Linux (the interpreter the same, and I don't know what the problem is). Maybe we can close this issue, but keep in mind that it's possible.

**Comment by glaslos** [comment]
I agree.
