### ISSUE TITLE
Run Failes after install

### ISSUE THREAD

**Issue by kevthehermit** [mushorg/tanner#91]
$ sudo tanner
Traceback (most recent call last):
  File "/usr/local/bin/tanner", line 4, in <module>
    __import__('pkg_resources').run_script('Tanner==0.1.0', 'tanner')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.1.0-py3.5.egg/EGG-INFO/scripts/tanner", line 21, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.1.0-py3.5.egg/EGG-INFO/scripts/tanner", line 16, in main
    config.TannerConfig.set_config(args.config)
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.1.0-py3.5.egg/tanner/config.py", line 12, in set_config
    TannerConfig.create_default_config(cfg, config_path)
  File "/usr/local/lib/python3.5/dist-packages/Tanner-0.1.0-py3.5.egg/tanner/config.py", line 23, in create_default_config
    with open(config_path, 'w') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/tanner/config.cfg'

**Comment by kevthehermit** [comment]
Looks like https://github.com/mushorg/tanner/pull/90 will fix

**Comment by afeena** [comment]
Please, let me know if something goes wrong with #90 :)

**Comment by glaslos** [comment]
Just merged #90 please check if that solves your issue.

**Comment by kevthehermit** [comment]
Looks good thanks
