### ISSUE TITLE
Error on css file with url parameter

### ISSUE THREAD

**Issue by X4mp** [mushorg/tanner#99]
I've cloned wordpress site which contains some .css files in the /wp-content structure.
When hosting the clone with SNARE a request to such a css leads to a 'FileNotFound' Error in Tanner and a response 500 Internal Server error on SNARE.

The tanner log contains following error log:
```
2017-02-08 15:20 INFO:tanner.server.HttpRequestHandler:handle_event: Requested path /wp-content/themes/quark/css/normalize.css?ver=3.0.2
2017-02-08 15:20 ERROR:tanner.server.HttpRequestHandler:log_exception: Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/server.py", line 92, in handle_request
    response_msg = yield from self.handle_event(data, self.redis_client)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/server.py", line 56, in handle_event
    detection = yield from self.base_handler.handle(data, session, path)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/base.py", line 74, in handle
    detection = yield from self.emulate(data, session, path)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/base.py", line 64, in emulate
    detection = yield from self.handle_get(path)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/base.py", line 53, in handle_get
    sqli = yield from self.emulators['sqli'].check_get_data(path)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/sqli.py", line 61, in check_get_data
    sqli = yield from self.check_sqli(query[1])
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/sqli.py", line 39, in check_sqli
    res = yield from _run_cmd(command)
  File "/usr/lib/python3.6/site-packages/Tanner-0.1.0-py3.6.egg/tanner/emulators/sqli.py", line 33, in _run_cmd
    proc = yield from asyncio.wait_for(asyncio.create_subprocess_exec(*cmd, stdout=PIPE), 5)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 212, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "uvloop/loop.pyx", line 2164, in __subprocess_run (uvloop/loop.c:39415)
  File "uvloop/handles/process.pyx", line 549, in uvloop.loop.UVProcessTransport.new (uvloop/loop.c:93764)
  File "uvloop/handles/process.pyx", line 87, in uvloop.loop.UVProcess._init (uvloop/loop.c:85151)
FileNotFoundError: [Errno 2] No such file or directory
2017-02-08 15:20 INFO:aiohttp.access:log: 127.0.0.1 - - [08/Feb/2017:15:20:49 +0000] "POST /event HTTP/1.1" 500 170 "-" "Python/3.6 aiohttp/1.2.0"
```

I'm not sure if it's an TANNER issue because of the ?ver=3.0.2 or an aiohttp/server.py issue.
I would fix it and propose a Pull Request, but I'm not sure what exactly causes the issue.

**Comment by afeena** [comment]
Hi, thanks for the issue!

It will be great if you make the pr :)

**Comment by X4mp** [comment]
I will, but can you give me a hint where to look at?

**Comment by afeena** [comment]
Just now I can't reproduce the problem. But I can make some suggestions.

Try to understand which file tanner can't find. 
``` res = yield from _run_cmd(command)```
You can just print the command and see what it try to do.

**Comment by X4mp** [comment]
OK I'll try that and investigate what the Problem is. But you would say the
Problem isn't with aiohttp (it's on top of the backtrace)?

**Comment by afeena** [comment]
No, it's not with aiohttp. See the latest call, not the first :) 
Example of the python stack trace with explanation https://en.wikipedia.org/wiki/Stack_trace

**Comment by X4mp** [comment]
Thx

**Comment by X4mp** [comment]
As @afeena linked, it was a problem with the dependecies.
